### ISSUE TITLE
variant-browser|opencb-test: detail panel, tab sample => null point exception error

### ISSUE THREAD

**Issue by pamag** [opencb/jsorolla#196]
**Describe the bug**
null point exception when selecting detail panel for "sample" in a variant browser variant

**To Reproduce**
[in docker opencb 2021-10-21 10:30GMT]
1. pull opencb docker
2. user demouser
3. go to variant browser
4. FILTER by gene BRCA1
5. select a variant
6. go to sample in detail panel 

![image](https://user-images.githubusercontent.com/167875/138261256-03bb8e6e-39b8-498c-976c-11aa0371faac.png)

## OPENCGA side:
```
curl 'https://ws.opencb.org/opencga-test/webservices/rest/v2/analysis/clinical/search?individual=%2C%2C&limit=3&study=demo%40family%3Aplatinum&include=id%2Cproband.id%2Cfamily.members' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'DNT: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vdXNlciIsImF1ZCI6Ik9wZW5DR0EgdXNlcnMiLCJpYXQiOjE2MzQ4MDgwNTIsImV4cCI6MTYzNDgxMTY1Mn0.aAmfcSNRt8vYelUQvfSlivUM9bGUwdjctonRbLEa6xc' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:9990' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:9990/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --compressed
```
stack trace
```
2021-10-21 10:09:38 [http-apr-8443-exec-22] INFO  OpenCGAWSServer:473 - GET: https://ws.opencb.org/opencga-test/webservices/rest/v2/analysis/clinical/search, {"study":"demo@family:platinum","individual":",,"}, {"metadata":true,"include":["id","proband.id","family.members"],"limit":3}
2021-10-21 10:09:38 [http-apr-8443-exec-22] ERROR OpenCGAWSServer:511 - Catch error: null
java.lang.NullPointerException: null
	at org.opencb.opencga.catalog.managers.ClinicalAnalysisManager.fixQueryObject(ClinicalAnalysisManager.java:1602) ~[opencga-catalog-2.2.0-SNAPSHOT.jar:?]
	at org.opencb.opencga.catalog.managers.ClinicalAnalysisManager.search(ClinicalAnalysisManager.java:1435) ~[opencga-catalog-2.2.0-SNAPSHOT.jar:?]
	at org.opencb.opencga.server.rest.analysis.ClinicalWebService.search(ClinicalWebService.java:301) [classes/:?]
```
OpenCGA return an `NPE`

## IVA side:

 IVA is sending `individual=,,`

note: reviewed with @j-coll the OpenCGA part

**Comment by pamag** [comment]
## Reviewed

commit: f104bd4712825f4c4fdc278c088a4b7b7bff1bf0

FIXED
